version: '2'

services:
  zookeeper:
    image: jplock/zookeeper:3.4.9
    networks:
      - back
        
  client:
    build:
      dockerfile: Dockerfile.client
      context: .
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    networks:
      - back
    environment:
      - LEIN_REPL_PORT=40001 
      - LEIN_REPL_HOST=0.0.0.0
    links:
      - zookeeper
    ports:
      - "0.0.0.0:40001:40001"

networks:
  back:
    driver: bridge
